targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - lib/modules/domain/models/**.dart
            - lib/modules/domain/services/**.dart
            - lib/modules/program_management/models/**.dart
            - lib/modules/program_management/services/text_plan/**.dart
            - lib/modules/program_management/services/text_plan/**.dart
            - lib/modules/workout_day_picker/models/**.dart
            - lib/modules/workout_day_picker/services/**.dart
            - lib/modules/workout_overview/models/**.dart
            - lib/modules/workout_overview/services/**.dart
      json_serializable:
        generate_for:
          include:
            - lib/modules/domain/models/**.dart
            - lib/modules/domain/services/**.dart
            - lib/modules/program_management/models/**.dart
            - lib/modules/program_management/services/text_plan/**.dart
        options:
          explicit_to_json: true
          include_if_null: false
          checked: true
      drift_dev:
        generate_for:
          include:
            - lib/modules/persistence/database/app_database.dart
            - lib/modules/persistence/database/tables.dart
        options:
          generate_connect_constructor: false
          sqlite_modules: []
