targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - lib/modules/domain/models/**.dart
            - lib/modules/program_management/models/**.dart
      json_serializable:
        generate_for:
          include:
            - lib/modules/domain/models/**.dart
        options:
          explicit_to_json: true
          include_if_null: false
          checked: true
      drift_dev:
        generate_for:
          include:
            - lib/modules/persistence/database/app_database.dart
            - lib/modules/persistence/database/tables.dart
        options:
          generate_connect_constructor: false
          sqlite_modules: []
