name: CI

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mobile

    steps:
      - uses: actions/checkout@v6

      - uses: subosito/flutter-action@v2.18.0
        with:
          channel: stable

      - name: Get dependencies
        run: flutter pub get

      - name: Make scripts executable
        run: chmod +x tool/check_offline_imports.sh

      - name: Check offline imports
        run: bash tool/check_offline_imports.sh

      - name: Run code generation
        run: dart run build_runner build --force-jit

      - name: Analyze
        run: flutter analyze

      - name: Test
        run: flutter test
